services:
  pocketbase:
    build:
      context: ./dockerfile/pocketbase
      args:
        PB_VERSION: ${PB_VERSION}
    expose:
      - "8090"
    environment:
      - TZ=Asia/Taipei
    volumes:
      # 把容器內的 pb_data 掛載出來，確保資料永久保存
      - ./pb_data:/pb/pb_data
      - ./pb_migrations:/pb/pb_migrations
      - ./pb_hooks:/pb/pb_hooks
    mem_limit: 512m
    container_name: pb-backend
    restart: always
    networks:
      - app-network

  svelte-app:
    build:
      context: .  # 根目錄
      dockerfile: ./dockerfile/svelte/Dockerfile
      args:
        APP_ENV: ${APP_ENV}  # dev for development, prod for production
        VITE_ALLOWED_HOSTS: ${VITE_ALLOWED_HOSTS}  # 允許的主機
    expose:
      - "3000"  # 只在網路內可用
    container_name: svelte-frontend
    restart: always
    environment:
      - POCKETBASE_URL=${POCKETBASE_URL}
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
      - BODY_SIZE_LIMIT=26214400
    volumes:
      - ./frontend:/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine  # 使用官方映像，無需 build
    ports:
      - "${WEB_PORT:-80}:80"  # env 關注開放 host 的 port
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # mount 配置
    depends_on:
      - pocketbase
      - svelte-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
